name: intern_task
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  connectivity_plus: ^3.0.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  chewie: ^1.3.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.1.1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  hive_generator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

  # assets: